name: Feature Validation

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]  # Testing on multiple Python versions

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter (pylint)
        run: |
          source env/bin/activate
          make lint

      - name: Run Tests (pytest)
        run: |
          source env/bin/activate
          make test

      - name: Check OS
        run: |
          if [[ "$OSTYPE" != "linux-gnu"* ]]; then
            echo "Error: OS is not Linux!"
            exit 1
          fi

      - name: Check Python Version
        run: |
          PYTHON_VERSION=$(python --version 2>&1)
          if [[ "$PYTHON_VERSION" != "Python 3.10"* ]] && [[ "$PYTHON_VERSION" != "Python 3.11"* ]]; then
            echo "Error: Python version is not 3.10 or 3.11!"
            exit 1
          fi
